var PIS = {
  type: jsPsychInstructions,
  pages: [ 
    `<img width="30%" src='img/tas.png'></img><h3>REGALS: Responsible 
      Employment of Generative AI for Legal Services.</h3>

    <h4>WWWWhy we are asking you to take part in our survey</h4> 
    <p>This research project seeks to understand people's willingness 
      to take legal advice from different sources. We are specifically 
      interested in comparing the advice generated by legal experts and 
      large language models. </p>

    <h4>Funder information</h4>
    <p>This research is funded by the Engineering and Physical Sciences 
      Council research project: UKRI Trustworthy Autonomous Systems Hub, 
      EP/V00784X/1, <a href="https://gow.epsrc.ukri.org/NGBOViewGrant.aspx?GrantRef=EP/V00784X/1" 
      target="_blank">https://gow.epsrc.ukri.org/NGBOViewGrant.aspx?GrantRef=EP/V00784X/1</a></p>
    
    <h4>Ethics</h4>
    <p>This research has received a favourable ethical opinion from the 
      School of Computer Science Research Ethics Committee (CS REC), ethics 
      application ID CS-2023-R22 </p>

    <h5>Legal basis for processing of the collected data</h5>
    <p>We collect personal data under the terms of the University of 
      Nottingham's Royal Charter and in our capacity as a teaching and 
      research body to advance education and learning. We thus process 
      your data on the legal basis that our research is in the public 
      interest, we have legitimate interests and / or that you consent 
      to data processing in freely and voluntarily participating in our 
      research activities.</p>

    <h4>Taking part in the survey</h4>
    <p>If you take part in this study, you will be asked to read a series 
      of legal advice texts. You may, or may not, know the source of the 
      legal texts. You will read each text and then rate your willingness 
      to follow the advice.</p>

    <h5>Risks of participation</h5>
    <p>No identifiable information will be collected during There is always 
      a risk of unauthorised access to data. The only identifiable 
      information that we will collect will be your name at the end of 
      this consent form. This information will be stripped from your main 
      data before data analysis occurs. As data collection will include 
      semi-structured interviews, this comes with the risk of interviewees 
      disclosing sensitive topics. To avoid this, we will inform 
      interviewees - prior to beginning the interview - that they should i) 
      try to avoid disclosing any sensitive information, and ii) that all 
      questions are optional, and they are free not to answer if they wish. 
      We will remind interviewees throughout the interview process, and 
      further re-iterate this at the end of the interview. Nonetheless, 
      the risk that attach to the research in terms of using your data 
      is that it may be possible identify you in research reports and 
      publications.
      
      <br><br>
    
      We keep your data securely and put measures in place to safeguard it. 
    All participants will be anonymized so that no participants will be 
    identifiable in the final analysis or report.</p>

    <h4>Data collection and purpose</h4>
    <p>We collect the following categories of data during your participation 
      in the research: Questionnaire responses</p>
    <p>We will use the collected survey data for</p>
      <ul>
        <li>The data collected by the questionnaire will be analysed to meet 
          the aims and objectives of our research described</li>
        <li>It may be reviewed and discussed in research meetings between 
          members of the research team</li>
        <li>Findings will be used to inform future studies in the REGALS 
          project, for example to create prompts for experimental studies.</li>
      </ul>        

    <h4>Your ethical rights</h4>
    <p>You have the right to withdraw at any time during the survey without 
      explanation. However, it will not be possible to delete any data you 
      provide after the questionnaire has been completed as the data is 
      anonymous and we cannot track who provided it.</p>`,
    ],
    show_clickable_nav: true,
    key_forward: " ",
    allow_backward: false
};

var consentQuestion = {
  type: jsPsychInstructions,
  pages: ['By clicking \"I agree\", you affirm that you are at least 18 years of age, which is the minimum age to participate in this study, and that you understand the nature of your participation in this research.<p>If you do not wish to participate, please close this window.'],
  show_clickable_nav: true,
  key_forward: " ",
  button_label_next: "I agree",
  allow_backward: false,
  data: {
      Condition: 'REMOVE', // For easier data processing
      Running: 'Consent'
    }
}


var consent = { timeline: [] };
consent.timeline.push(PIS, consentQuestion);

var debrief = {
  type: 'instructions',
  pages:
      [
          '<p><img src="images/logo.png" width="254px" height="55px" style="float:left"></img>' +

          '<br><br><p style = "left:3%; text-align: left;"><b>Guessing and memory<br>Debriefing statement </b><i>(written) </i>(Version no 1, 20/10/19)<br><b>ERGO ID: 52932</b>' +

          '<br><br>The aim of this research was to explore the effects of guessing on memory. Past research suggests that people tend to remember an answer better when they have first guessed the answer, compared to when they just study the answer (Kornell, Hays, & Bjork, 2009). Importantly, this pattern is apparent even when participants\' guesses are wrong (Potts & Shanks, 2014). The current research aims to examine why guesses are beneficial for memory, and the conditions in which guesses improve memory.' +

          '<br><br>Your data will help our understanding of the conditions in which taking tests help and hinder learning and memory. Once again results of this study will not include your name or any other identifying characteristics.  The experiment did not use deception. You may have a copy of this summary if you wish. Additionally, if you would like further information about this area of research then you may wish to look up the following references: ' +

          '<br><br>Kornell, N., Hays, M., & Bjork, R. A. (2009). Unsuccessful retrieval attempts enhance subsequent learning. <i>Journal of Experimental Psychology: Learning, Memory, and Cognition, 35</i>(4), 989-998. https://doi.org/10.1037/a0015729' +
          '<br><br>Potts, R., & Shanks, D. R. (2014). The benefit of generating errors during learning. <i>Journal of Experimental Psychology: General, 143</i>(2), 644-667. https://doi.org/10.1017/CBO9781107415324.004' +

          '<br><br><b>Important:</b> Please do not share the information we provide in this section with anyone who has not yet completed the experiment (e.g., by telling them what you did during the study, or why you were asked to do it). This may change their responses if they go on to complete the study, and it could jeopardise the project. Thank you for your participation in this research.' +

          '<br><br>Signature: T.SEABROOKE, Date 20/10/19 <br> Name: Dr Tina Seabrooke' +

          '<br><br>If you have questions about your rights as a participant in this research, or if you feel that you have been placed at risk, you may contact the University of Southampton Research Integrity and Governance Manager(023 8059 5058, rgoinfo@soton.ac.uk).'
      ],
  show_clickable_nav: true,
  data: {
      Condition: 'REMOVE', // For easier data processing
      Running: 'Debrief'
  }
};