var PIS = {
  type: jsPsychInstructions,
  pages: [ 
    `<img width="30%" src='img/tas.png'></img><h3>REGALS: Responsible 
      Employment of Generative AI for Legal Services.</h3>

    <h4>WWWWhy we are asking you to take part in our survey</h4> 
    <p>This research project seeks to understand people's willingness 
      to take legal advice from different sources. We are specifically 
      interested in comparing the advice generated by legal experts and 
      large language models. </p>

    <h4>Funder information</h4>
    <p>This research is funded by the Engineering and Physical Sciences 
      Council research project: UKRI Trustworthy Autonomous Systems Hub, 
      EP/V00784X/1, <a href="https://gow.epsrc.ukri.org/NGBOViewGrant.aspx?GrantRef=EP/V00784X/1" 
      target="_blank">https://gow.epsrc.ukri.org/NGBOViewGrant.aspx?GrantRef=EP/V00784X/1</a></p>
    
    <h4>Ethics</h4>
    <p>This research has received a favourable ethical opinion from the 
      School of Computer Science Research Ethics Committee (CS REC), ethics 
      application ID CS-2023-R22 </p>

    <h5>Legal basis for processing of the collected data</h5>
    <p>We collect personal data under the terms of the University of 
      Nottingham's Royal Charter and in our capacity as a teaching and 
      research body to advance education and learning. We thus process 
      your data on the legal basis that our research is in the public 
      interest, we have legitimate interests and / or that you consent 
      to data processing in freely and voluntarily participating in our 
      research activities.</p>

    <h4>Taking part in the survey</h4>
    <p>If you take part in this study, you will be asked to read a series 
      of legal advice texts. You may, or may not, know the source of the 
      legal texts. You will read each text and then rate your willingness 
      to follow the advice.</p>

    <h5>Risks of participation</h5>
    <p>No identifiable information will be collected during There is always 
      a risk of unauthorised access to data. The only identifiable 
      information that we will collect will be your name at the end of 
      this consent form. This information will be stripped from your main 
      data before data analysis occurs. As data collection will include 
      semi-structured interviews, this comes with the risk of interviewees 
      disclosing sensitive topics. To avoid this, we will inform 
      interviewees - prior to beginning the interview - that they should i) 
      try to avoid disclosing any sensitive information, and ii) that all 
      questions are optional, and they are free not to answer if they wish. 
      We will remind interviewees throughout the interview process, and 
      further re-iterate this at the end of the interview. Nonetheless, 
      the risk that attach to the research in terms of using your data 
      is that it may be possible identify you in research reports and 
      publications.
      
      <br><br>
    
      We keep your data securely and put measures in place to safeguard it. 
    All participants will be anonymized so that no participants will be 
    identifiable in the final analysis or report.</p>

    <h4>Data collection and purpose</h4>
    <p>We collect the following categories of data during your participation 
      in the research: Questionnaire responses</p>
    <p>We will use the collected survey data for</p>
      <ul>
        <li>The data collected by the questionnaire will be analysed to meet 
          the aims and objectives of our research described</li>
        <li>It may be reviewed and discussed in research meetings between 
          members of the research team</li>
        <li>Findings will be used to inform future studies in the REGALS 
          project, for example to create prompts for experimental studies.</li>
      </ul>        

    <h4>Your ethical rights</h4>
    <p>You have the right to withdraw at any time during the survey without 
      explanation. However, it will not be possible to delete any data you 
      provide after the questionnaire has been completed as the data is 
      anonymous and we cannot track who provided it.</p>`,
    ],
    show_clickable_nav: true,
    key_forward: " ",
    allow_backward: false
};

var consentQuestion = {
  type: jsPsychInstructions,
  pages: [
    'By clicking \"I agree\", you affirm that you are at least 18 years of age, ' +
    'which is the minimum age to participate in this study, and that you understand ' +
    'the nature of your participation in this research.<p>If you do not wish to ' +
    'participate, please close this window.'
  ],
  show_clickable_nav: true,
  key_forward: " ",
  button_label_next: "I agree",
  allow_backward: false,
  data: {
      Condition: 'REMOVE', // For easier data processing
      Running: 'Consent'
    }
}


var consent = { timeline: [] };
consent.timeline.push(PIS, consentQuestion);

var debrief = {
  type: jsPsychInstructions,
  pages:
      [
          '<p><img src="img/tas.png" width="30%" style="float:left"></img>' +
          'Debrief with some relevant info...'
      ],
  show_clickable_nav: false,
  data: {
      Condition: 'REMOVE', // For easier data processing
      Running: 'Debrief'
  }
};

consent.timeline.push(debrief)