var PIS = {
  type: jsPsychInstructions,
  pages: [ 
    `<img width="30%" src='img/tas.png'></img><h3>REGALS: Responsible 
      Employment of Generative AI for Legal Services.</h3>

    <h4>Why we are asking you to take part in our survey</h4> 
    <p>This research project seeks to understand people's willingness 
      to take legal advice from different sources. We are specifically 
      interested in comparing the advice generated by legal experts and 
      large language models. </p>

    <h4>Funder information</h4>
    <p>This research is funded by the Engineering and Physical Sciences 
      Council research project: UKRI Trustworthy Autonomous Systems Hub, 
      EP/V00784X/1, <a href="https://gow.epsrc.ukri.org/NGBOViewGrant.aspx?GrantRef=EP/V00784X/1" 
      target="_blank">https://gow.epsrc.ukri.org/NGBOViewGrant.aspx?GrantRef=EP/V00784X/1</a></p>
    
    <h4>Ethics</h4>
    <p>This research has received a favourable ethical opinion from the 
      School of Computer Science Research Ethics Committee (CS REC), ethics 
      application ID CS-2023-R22.</p>

    <h5>Legal basis for processing of the collected data</h5>
    <p>We collect personal data under the terms of the University of 
      Nottingham's Royal Charter and in our capacity as a teaching and 
      research body to advance education and learning. We thus process 
      your data on the legal basis that our research is in the public 
      interest, we have legitimate interests and / or that you consent 
      to data processing in freely and voluntarily participating in our 
      research activities.</p>

    <h4>Taking part in the survey</h4>
    <p>If you take part in this study, you will be asked to read a series 
      of legal advice texts. You may, or may not, know the source of the 
      legal texts. You will read each text and then rate your willingness 
      to follow the advice.</p>

    <h5>Risks of participation</h5>
    <p>No identifiable information will be collected during this study. 
    There is always a risk of unauthorised access to data. The only identifiable 
      information that we will collect will be your name at the end of 
      this consent form. This information will be stripped from your main 
      data before data analysis occurs.

      <br><br>
    
      We keep your data securely and put measures in place to safeguard it. 
    All participants will be anonymized so that no participants will be 
    identifiable in the final analysis or report.</p>

    <h4>Data collection and purpose</h4>
    <p>We collect the following categories of data during this study: 
    Questionnaire responses</p>
    <p>We will use the collected survey data for</p>
      <ul>
        <li>The data collected by the questionnaire will be analysed to meet 
          the aims and objectives of our research described</li>
        <li>It may be reviewed and discussed in research meetings between 
          members of the research team</li>
        <li>Findings will be used to inform future studies in the REGALS 
          project, for example to create prompts for experimental studies.</li>
      </ul>        

    <h4>Your ethical rights</h4>
    <p>You have the right to withdraw at any time during the survey without 
      explanation. However, it will not be possible to delete any data you 
      provide after the questionnaire has been completed as the data is 
      anonymous and we cannot track who provided it.</p>`,
    ],
    show_clickable_nav: true,
    key_forward: " ",
    allow_backward: false
};

var consentQuestion = {
  type: jsPsychInstructions,
  pages: [
    'By clicking \"I agree\", you affirm that you are at least 18 years of age, ' +
    'which is the minimum age to participate in this study, and that you understand ' +
    'the nature of your participation in this research.<p>If you do not wish to ' +
    'participate, please close this window.'
  ],
  show_clickable_nav: true,
  key_forward: " ",
  button_label_next: "I agree",
  allow_backward: false,
  data: {
      Condition: 'REMOVE', // For easier data processing
      Running: 'Consent'
    }
}


var consent = { timeline: [] };
consent.timeline.push(PIS, consentQuestion);

var debrief = {
  type: jsPsychInstructions,
  pages:
      [
          '<p><img src="img/tas.png" width="30%" style="float:left"></img>' +
          
          '<br><br><p style = "left:3%; text-align: left;"><b>REGALS: Responsible Employment of Generative AI for Legal Services.<br>Debriefing statement </b><i>(written) </i>(Version no 1, 06/06/24)<br><b>Approved ethics application: CS-2023-R22</b>' +

          '<br><br>The aim of this research was to explore people\'s willingness to act on legal advice generated from two different source: lawyer\'s and Large Language Models.' +

          '<br><br>Your data will help us understand the risks asociated with the use of LLMs in the legal context for non-legal experts. Furthermore, it will help us identify the importance the source has on people\'s truwst in legal advice presented.' +

          '<br><br><b>Important:</b> Please do not use the here presented advice, lawyer or LLM generated, outside of this study. Thank you for your participation in this research.' +

          '<br><br>Signature: E.Schneiders, Date 06/06/24 <br> Name: Dr Eike Schneiders' +

          '<br><br>If you have questions about your rights as a participant in this research, or if you feel that you have been placed at risk, you may contact the University of Nottingham Research Integrity and Governance Manager (XXXXXXXXX, XXX@XXX.co.uk).'
      ],
  show_clickable_nav: false,
  data: {
      Condition: 'REMOVE', // For easier data processing
      Running: 'Debrief'
  }
};